apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-rc
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-rc
  template:
    metadata:
      labels:
        app: python-rc
    spec:
      containers:
        - name: python-rc
          image: tothg/python-web-rc:latest
          ports:
          - containerPort: 5050
          resources:
            requests:
              cpu: "250m"

---
kind: Service
apiVersion: v1
metadata:
  name: web-service
spec:
  type: NodePort
  selector:
    app: python-rc
  ports:
    - port: 5050
      nodePort: 32000
      protocol: TCP
      name: http
